export const championPositions: Record<string, string[]> = {
  // === TOP 포지션 ===
  Ambessa: ["TOP"],
  Aurora: ["TOP", "MID"],
  Fiora: ["TOP"],
  Pantheon: ["MID", "JUG", "SUP", "TOP"],
  Shyvana: ["TOP", "JUG"],
  Tahmkench: ["SUP", "TOP"],
  Garen: ["TOP"],
  Gangplank: ["TOP"],
  Gragas: ["TOP", "JUG", "SUP"],
  Gwen: ["TOP", "JUG"],
  Gnar: ["TOP"],
  Nasus: ["TOP"],
  Nocturne: ["JUG", "TOP"],
  Darius: ["TOP"],
  Ryze: ["MID", "TOP"],
  Rumble: ["TOP"],
  Renekton: ["TOP"],
  Rengar: ["JUG", "TOP"],
  Riven: ["TOP"],
  Maokai: ["TOP", "SUP"],
  Malphite: ["TOP", "MID"],
  Mordekaiser: ["TOP"],
  Drmundo: ["TOP"],
  Volibear: ["TOP", "JUG"],
  Vladimir: ["TOP", "MID"],
  Poppy: ["TOP", "JUG", "SUP"],
  Sion: ["TOP"],
  Sett: ["TOP", "SUP"],
  Shen: ["TOP", "SUP"],
  Singed: ["TOP"],
  Aatrox: ["TOP"],
  Urgot: ["TOP"],
  Ornn: ["TOP"],
  Wukong: ["TOP", "JUG"],
  Olaf: ["JUG", "TOP"],
  Yorick: ["TOP"],
  Yone: ["TOP", "MID"],
  Irelia: ["TOP", "MID"],
  Illaoi: ["TOP"],
  Jax: ["TOP", "JUG"],
  Jayce: ["TOP", "MID"],
  Chogath: ["TOP"],
  Camille: ["TOP"],
  Kennen: ["TOP"],
  Kayle: ["TOP"],
  Quinn: ["TOP"],
  Kled: ["TOP"],
  Teemo: ["TOP"],
  Ksante: ["TOP"],
  Heimerdinger: ["TOP"],

  // === JUNGLE 포지션 ===
  Nidalee: ["JUG"],
  Naafiri: ["JUG", "MID"],
  Diana: ["JUG", "MID"],
  "Nunu&willump": ["JUG"],
  Shaco: ["JUG"],
  Talon: ["MID", "JUG"],
  Khazix: ["JUG"],
  Rammus: ["JUG"],
  Xinzhao: ["JUG"],
  Reksai: ["JUG"],
  Belveth: ["JUG"],
  Leesin: ["JUG"],
  Lillia: ["JUG"],
  Masteryi: ["JUG"],
  Vi: ["JUG"],
  Veigar: ["MID"],
  Viego: ["JUG"],
  Skarner: ["JUG"],
  Sejuani: ["JUG"],
  Amumu: ["JUG"],
  Ivern: ["JUG"],
  Elise: ["JUG"],
  Udyr: ["JUG"],
  Evelynn: ["JUG"],
  Jarvaniv: ["JUG"],
  Karthus: ["JUG", "MID"],
  Kayn: ["JUG"],
  Kindred: ["JUG"],
  Trundle: ["JUG", "TOP"],
  Fiddlesticks: ["JUG"],
  Hecarim: ["JUG"],
  Graves: ["JUG"],
  Briar: ["JUG"],
  Warwick: ["JUG", "TOP"],
  Ekko: ["MID", "JUG"],
  Zac: ["JUG", "TOP"],

  // === MID 포지션 ===
  Galio: ["MID", "SUP"],
  Lux: ["MID", "SUP"],
  Lisandra: ["MID"],
  RekSai: ["JUG"],
  Malzahar: ["MID"],
  Neeko: ["MID", "SUP"],
  Velkoz: ["MID", "SUP"],
  Viktor: ["MID"],
  Sylas: ["MID", "TOP", "JUG"],
  Swain: ["MID", "SUP"],
  Leblanc: ["MID", "SUP"],
  Syndra: ["MID"],
  Aurelionsol: ["MID"],
  Ahri: ["MID"],
  Azir: ["MID"],
  Akali: ["MID", "TOP"],
  Annie: ["MID"],
  Anivia: ["MID"],
  Yasuo: ["MID", "TOP"],
  Orianna: ["MID"],
  Vex: ["MID", "JUG"],
  Zed: ["MID", "JUG"],
  Xerath: ["MID"],
  Seraphine: ["SUP", "MID"],
  Zoe: ["MID"],
  Ziggs: ["MID", "ADC"],
  Kassadin: ["MID"],
  Cassiopeia: ["MID"],
  Katarina: ["MID"],
  Corki: ["MID", "ADC"],
  Qiyana: ["MID"],
  Twistedfate: ["MID"],
  Taliyah: ["MID", "JUG"],
  Fizz: ["MID"],
  Hwei: ["MID"],
  Jhin: ["ADC"],
  Jinx: ["ADC"],
  Kai: ["ADC"],
  Kaisa: ["ADC"],
  Caitlyn: ["ADC"],
  Kogmaw: ["ADC"],

  // === ADC/BOTTOM 포지션 ===
  Nilah: ["ADC"],
  Draven: ["ADC"],
  Lucian: ["ADC"],
  Mel: ["ADC", "SUP"],
  Missfortune: ["ADC"],
  Varus: ["ADC"],
  Vayne: ["ADC"],
  Yunara: ["ADC"],
  Samira: ["ADC"],
  Senna: ["ADC", "SUP"],
  Smolder: ["ADC"],
  Xayah: ["ADC"],
  Zeri: ["ADC"],
  Sivir: ["ADC"],
  Aphelios: ["ADC"],
  Ashe: ["ADC"],
  Ezreal: ["ADC"],
  Kalista: ["ADC"],
  Tristana: ["ADC", "MID"],
  Twitch: ["ADC"],

  // === SUPPORT 포지션 ===
  Nami: ["SUP"],
  Nautilus: ["SUP"],
  Renataglasc: ["SUP"],
  Milio: ["SUP"],
  Yuumi: ["SUP"],
  Soraka: ["SUP"],
  Taric: ["SUP"],
  Leona: ["SUP"],
  Rakan: ["SUP"],
  Lulu: ["SUP"],
  Rell: ["SUP"],
  Morgana: ["SUP", "MID"],
  Bard: ["SUP"],
  Blitzcrank: ["SUP"],
  Braum: ["SUP"],
  Pyke: ["SUP"],
  Thresh: ["SUP"],
  Alistar: ["SUP"],
  Zyra: ["SUP", "JUG"],
  Lissandra: ["MID"],
  Janna: ["SUP"],
  Zilean: ["SUP"],
  Karma: ["SUP"],
};
