/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schedule/sync/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 과거 경기 이력 수동 동기화
         * @description Lolesports의 모든 대상 리그에 대해 과거 경기 이력을 수동으로 동기화합니다.
         */
        post: operations["syncHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{playerId}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 선수 이미지 URL 수동 업데이트
         * @description 특정 선수의 이미지 URL을 수동으로 업데이트합니다.
         */
        post: operations["updatePlayerImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/sync-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LCK 선수 프로필 일괄 동기화
         * @description LCK 리그 선수들의 프로필 정보를 TrackingThePros에서 크롤링하여 DB에 저장합니다. 실패한 선수 목록을 반환합니다.
         */
        post: operations["syncLckPlayerProfiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/sync-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LCK 선수 이미지 URL 일괄 동기화
         * @description LCK 선수들의 이미지 URL을 확인하고 유효한 경우 업데이트하며, 실패한 선수 목록을 반환합니다.
         */
        post: operations["syncLckPlayerImages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/riot/sync-primary-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LCK 선수 주 계정 Riot 식별자 동기화
         * @description KR 주 계정의 riotId를 기준으로 puuid를 조회해 추적 테이블에 저장합니다.
         */
        post: operations["syncPrimaryRiotAccounts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/riot/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 선수 솔랭 감시 수동 실행
         * @description KR 주 계정 추적 대상에 대해 spectator-v5 현재 게임 상태를 확인하고 솔랭 시작 알림을 전송합니다.
         */
        post: operations["pollTrackedPlayers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/riot/manual-alert-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 선수 솔랭 알림 수동 체크
         * @description 관리자용 API입니다. puuid로 spectator-v5 현재 게임을 조회하고, 솔랭이면 실제 디스코드 알림을 즉시 전송합니다.
         */
        post: operations["checkAndSendRiotAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kakao/skills/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kakao/skills/lck-schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getLckSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/champions/{championId}/loading-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 챔피언 로딩 이미지 URL 수동 업데이트
         * @description 카드 배경용 loading 이미지 URL을 챔피언에 저장합니다.
         */
        post: operations["updateChampionLoadingImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/champions/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 챔피언 데이터 동기화 (관리자용)
         * @description 챔피언 데이터를 가져와 DB를 갱신합니다.
         */
        post: operations["syncChampions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/champions/loading-image/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 전체 챔피언 로딩 이미지 URL 일괄 업데이트
         * @description 모든 챔피언의 loading 이미지 URL을 자동 생성해 저장합니다.
         */
        post: operations["updateAllChampionLoadingImages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/search/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 전체 동기화
         * @description MySQL의 Team, Player 데이터를 Elasticsearch에 동기화
         */
        post: operations["syncAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/search/sync/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 팀 동기화
         * @description Team 데이터만 동기화
         */
        post: operations["syncTeams"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/search/sync/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 선수 동기화
         * @description Player 데이터만 동기화
         */
        post: operations["syncPlayers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 경기 자동완성 검색
         * @description 팀 vs 팀 형식의 검색어로 관련 경기를 자동완성 검색합니다. 예: 'T1 vs Geng', 'T1vsGeng', 't1 geng'
         */
        get: operations["autocomplete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamId}/radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 레이더 차트 통계
         * @description 팀의 22개 지표 레이더 차트 데이터를 반환합니다. 리그 평균과 비교할 수 있습니다.
         */
        get: operations["getTeamRadarStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamId}/profile-header": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 프로필 헤더
         * @description 팀명/로고와 최근 경기 일정 3개를 반환합니다.
         */
        get: operations["getTeamProfileHeader"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamId}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 페이지 대시보드
         * @description 게임요약, 선수기록, 밴당한/밴한 챔피언, 플레이한 챔피언을 필터 기준으로 한 번에 반환합니다.
         */
        get: operations["getTeamDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/scatter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 지표 스캐터 차트
         * @description 리그/연도 기준으로 팀별 승률(y축)과 평균 지표(x축: ALL, KILLS, GOLD, OBJECTIVES) 데이터를 반환합니다.
         */
        get: operations["getTeamScatterStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 랭킹 조회
         * @description 필터 기준에 따른 팀 랭킹과 라인별 모스트 픽 챔피언을 조회합니다.
         */
        get: operations["getTeamRankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/detail-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 경기 데이터 상세
         * @description 팀 승률 기준 내림차순으로 매치/세트 전적과 킬/골드/오브젝트/퍼스트 오브젝트 지표를 반환합니다.
         */
        get: operations["getTeamDetailStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/story/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최신 영상 목록 조회
         * @description 카테고리, 정렬, 기간별로 영상을 조회합니다.
         */
        get: operations["getVideos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/story/videos/{videoId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 영상 댓글 조회
         * @description 특정 영상의 댓글을 최신순 또는 인기순으로 조회합니다.
         */
        get: operations["getVideoComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 일별 경기 일정 조회
         * @description 특정 날짜의 경기 목록을 조회합니다. (캘린더 클릭 시 사용)
         */
        get: operations["getDailySchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule/matches/{matchId}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 매치 상세 정보 조회
         * @description 특정 매치(Match)의 세부 정보를 조회합니다.
         */
        get: operations["getMatchDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 월별 경기 존재 날짜 조회
         * @description 특정 월에 경기가 있는 날짜와 경기 수를 조회합니다. (달력 마킹용)
         */
        get: operations["getMonthlyScheduleCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/profile/{gameName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 선수 프로필 크롤링
         * @description TrackingThePros에서 선수 프로필 정보(본명, 생년월일, 팀, 포지션 등)를 크롤링합니다.
         */
        get: operations["getPlayerProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 선수 카드 목록 조회
         * @description 년도/스플릿/패치/진영 필터로 선수 카드 목록(모스트 챔피언 3개 + 선수 상세)을 조회합니다.
         */
        get: operations["getPlayerCards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kakao/skills/images/matches/{matchId}.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMatchThumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 경기 일정 조회 (날짜별)
         * @description 특정 날짜의 모든 리그 경기 일정을 조회합니다. 날짜 미입력 시 전체 리그의 최신 경기를 반환합니다. [state : (completed, unstarted, inProgress)]
         */
        get: operations["getSchedule_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home/player/top5": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최근 패치 선수 통계 TOP 5 조회
         * @description LCK 리그의 최신 패치 기준 KDA, GPM, DPM 상위 5명 선수를 조회합니다.
         */
        get: operations["getTop5Players"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최신 뉴스 TOP 5 조회
         * @description 네이버 이스포츠 뉴스의 최신 상위 5개 기사를 조회합니다.
         */
        get: operations["getTop5News"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home/community": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 커뮤니티 TOP 5 조회
         * @description 통합 커뮤니티(OP.GG, Inven, Naver)의 상위 5개 게시글을 조회합니다.
         */
        get: operations["getTop5CommunityPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home/champion/top5": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최근 패치 모스트 챔피언 TOP 5 조회
         * @description LCK 리그의 가장 최신 패치 버전에서 픽률이 높은 상위 5개 챔피언의 통계(승률, 경기수)를 조회합니다.
         */
        get: operations["getTop5Champions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최근 게임 목록 검색
         * @description 리그, 시즌, 팀 필터를 적용하여 최근 게임 목록을 페이징 처리해 반환합니다.
         */
        get: operations["getRecentGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{gameId}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 게임 상세 데이터 조회
         * @description 게임 ID(gameId)를 통해 해당 매치의 밴픽, 선수별 스탯, 골드 차이 등 상세 정보를 반환합니다.
         */
        get: operations["getGameRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/combinations/{combinationId}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 조합 상세 분석
         * @description 특정 조합 ID를 기반으로 상세 게임 데이터를 조회합니다.
         */
        get: operations["getCombinationDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/combinations/stat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 데이터 업데이트 현황
         * @description 마지막 데이터 업데이트 시간을 조회합니다.
         */
        get: operations["getUpdateInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/combinations/matchups/1v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 1vs1 라인전 매치업 조회
         * @description 두 챔피언 간의 1:1 상대 전적 및 지표를 조회합니다.
         */
        get: operations["get1v1Matchup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/combinations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 챔피언 조합 조회
         * @description 선택한 챔피언들의 조합 승률, 픽률 데이터를 조회합니다.
         */
        get: operations["getCombinationsV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/champions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전체 챔피언 목록 조회
         * @description 등록된 모든 챔피언의 정보를 조회합니다.
         */
        get: operations["getAllChampions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카테고리 계층 구조 조회
         * @description 리그 > 시즌 > 팀 순서로 구성된 전체 트리 데이터를 반환합니다.
         */
        get: operations["getCategoryTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 전체 선수 이미지 URL 초기화
         * @description 모든 선수의 이미지 URL을 null로 초기화합니다.
         */
        delete: operations["resetAllPlayerImages"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PlayerProfileSyncResult: {
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            successCount?: number;
            /** Format: int32 */
            failCount?: number;
            failedPlayers?: string[];
        };
        PlayerImageSyncResult: {
            /** Format: int32 */
            totalTarget?: number;
            /** Format: int32 */
            successCount?: number;
            /** Format: int32 */
            failCount?: number;
            failedPlayerNames?: string[];
        };
        PlayerRiotAccountSyncResult: {
            /** Format: int32 */
            totalPlayers?: number;
            /** Format: int32 */
            syncedCount?: number;
            /** Format: int32 */
            skippedCount?: number;
            /** Format: int32 */
            failedCount?: number;
            skippedPlayers?: string[];
            failedPlayers?: string[];
        };
        PlayerSoloRankMonitorResult: {
            /** Format: int32 */
            totalTrackedAccounts?: number;
            /** Format: int32 */
            checkedCount?: number;
            /** Format: int32 */
            noRecentMatchCount?: number;
            /** Format: int32 */
            unchangedCount?: number;
            /** Format: int32 */
            otherQueueCount?: number;
            /** Format: int32 */
            rankedSoloCount?: number;
            /** Format: int32 */
            alertsSentCount?: number;
            /** Format: int32 */
            failedCount?: number;
        };
        PlayerRiotAlertCheckRequest: {
            puuid: string;
        };
        PlayerRiotAlertCheckResult: {
            puuid?: string;
            currentGameFound?: boolean;
            rankedSolo?: boolean;
            notificationSent?: boolean;
            gameId?: string;
            /** Format: int32 */
            queueId?: number;
            queueName?: string;
            riotId?: string;
            championName?: string;
            championIconUrl?: string;
            status?: string;
        };
        KakaoSkillRequest: {
            userRequest?: components["schemas"]["UserRequest"];
        };
        UserRequest: {
            utterance?: string;
        };
        BasicCard: {
            title?: string;
            description?: string;
            thumbnail?: string;
            buttons?: components["schemas"]["Button"][];
        };
        Button: {
            action?: string;
            label?: string;
            webLinkUrl?: string;
            messageText?: string;
        };
        KakaoSkillResponse: {
            version?: string;
            template?: components["schemas"]["Template"];
        };
        Link: {
            web?: string;
            mobile?: string;
            pc?: string;
        };
        ListCard: {
            header?: components["schemas"]["ListItem"];
            items?: components["schemas"]["ListItem"][];
            buttons?: components["schemas"]["Button"][];
            buttonLayout?: string;
        };
        ListItem: {
            title?: string;
            description?: string;
            imageUrl?: string;
            link?: components["schemas"]["Link"];
        };
        Output: {
            simpleText?: components["schemas"]["SimpleText"];
            textCard?: components["schemas"]["TextCard"];
            basicCard?: components["schemas"]["BasicCard"];
            listCard?: components["schemas"]["ListCard"];
        };
        QuickReply: {
            action?: string;
            label?: string;
            messageText?: string;
        };
        SimpleText: {
            text?: string;
        };
        Template: {
            outputs?: components["schemas"]["Output"][];
            quickReplies?: components["schemas"]["QuickReply"][];
        };
        TextCard: {
            title?: string;
            description?: string;
            buttons?: components["schemas"]["Button"][];
            buttonLayout?: string;
        };
        MatchSuggestionDto: {
            /** Format: int64 */
            gameId?: number;
            blueTeamName?: string;
            blueTeamCode?: string;
            blueTeamImageUrl?: string;
            /** Format: int32 */
            blueTeamScore?: number;
            redTeamName?: string;
            redTeamCode?: string;
            redTeamImageUrl?: string;
            /** Format: int32 */
            redTeamScore?: number;
            blueWin?: boolean;
            leagueName?: string;
            /** Format: date-time */
            gameDate?: string;
            patch?: string;
        };
        SearchAutocompleteResponse: {
            suggestions?: components["schemas"]["MatchSuggestionDto"][];
        };
        TeamRadarResponse: {
            stats?: components["schemas"]["TeamRadarStatsDto"];
            leagueAverage?: components["schemas"]["TeamRadarStatsDto"];
        };
        TeamRadarStatsDto: {
            /** Format: int64 */
            teamId?: number;
            teamName?: string;
            /** Format: int32 */
            gamesPlayed?: number;
            /** Format: int32 */
            year?: number;
            /** Format: double */
            winRate?: number;
            /** Format: double */
            goldDiffAt10?: number;
            /** Format: double */
            goldDiffAt15?: number;
            /** Format: double */
            goldDiffAt20?: number;
            /** Format: double */
            goldDiffAt25?: number;
            /** Format: double */
            gspd?: number;
            /** Format: double */
            ckpm?: number;
            /** Format: double */
            firstBloodRate?: number;
            /** Format: double */
            firstTowerRate?: number;
            /** Format: double */
            firstThreeTowerRate?: number;
            /** Format: double */
            firstHeraldRate?: number;
            /** Format: double */
            firstDragonRate?: number;
            /** Format: double */
            firstBaronRate?: number;
            /** Format: double */
            dragonsPerGame?: number;
            /** Format: double */
            voidGrubsRate?: number;
            /** Format: double */
            towersKilledAvg?: number;
            /** Format: double */
            towersLostAvg?: number;
            /** Format: double */
            earlyGameRating?: number;
            /** Format: double */
            midLateRating?: number;
            /** Format: double */
            pointsPerGame?: number;
        };
        TeamProfileHeaderResponse: {
            /** Format: int64 */
            teamId?: number;
            teamName?: string;
            teamCode?: string;
            teamImageUrl?: string;
            socialLinks?: components["schemas"]["TeamSocialLinks"];
            recentMatches?: components["schemas"]["TeamRecentMatchDto"][];
        };
        TeamRecentMatchDto: {
            matchId?: string;
            leagueName?: string;
            state?: string;
            scheduledAt?: string;
            relativeLabel?: string;
            blueTeamCode?: string;
            blueTeamName?: string;
            redTeamCode?: string;
            redTeamName?: string;
            /** Format: int32 */
            blueScore?: number;
            /** Format: int32 */
            redScore?: number;
        };
        TeamSocialLinks: {
            homepage?: string;
            instagram?: string;
            youtube?: string;
            twitter?: string;
        };
        TeamBanSideStatsDto: {
            all?: components["schemas"]["TeamBanStatDto"][];
            blue?: components["schemas"]["TeamBanStatDto"][];
            red?: components["schemas"]["TeamBanStatDto"][];
        };
        TeamBanStatDto: {
            /** Format: int64 */
            championId?: number;
            championNameKr?: string;
            championNameEn?: string;
            championImageUrl?: string;
            /** Format: int32 */
            banCount?: number;
            /** Format: double */
            banRatePct?: number;
        };
        TeamDashboardFilterDto: {
            /** Format: int32 */
            year?: number;
            split?: string;
            patch?: string;
            side?: string;
        };
        TeamDashboardResponse: {
            /** Format: int64 */
            teamId?: number;
            teamName?: string;
            teamCode?: string;
            teamImageUrl?: string;
            leagueName?: string;
            appliedFilter?: components["schemas"]["TeamDashboardFilterDto"];
            gameSummary?: components["schemas"]["TeamGameSummaryDto"];
            playerRecords?: components["schemas"]["TeamPlayerRecordDto"][];
            bannedAgainst?: components["schemas"]["TeamBanSideStatsDto"];
            bannedByTeam?: components["schemas"]["TeamBanSideStatsDto"];
            playedChampions?: components["schemas"]["TeamPlayedChampionSideStatsDto"];
        };
        TeamGameSummaryDto: {
            /** Format: int32 */
            matchesPlayed?: number;
            /** Format: int32 */
            matchWins?: number;
            /** Format: int32 */
            matchLosses?: number;
            /** Format: int32 */
            setsPlayed?: number;
            /** Format: int32 */
            setWins?: number;
            /** Format: int32 */
            setLosses?: number;
            /** Format: double */
            winRatePct?: number;
            /** Format: double */
            avgKills?: number;
            /** Format: double */
            avgGold?: number;
            /** Format: double */
            avgBarons?: number;
            /** Format: double */
            avgDragons?: number;
            /** Format: double */
            avgTowers?: number;
            /** Format: int32 */
            firstBloodCount?: number;
            /** Format: int32 */
            firstTowerCount?: number;
            /** Format: int32 */
            firstDragonCount?: number;
            /** Format: int32 */
            firstHeraldCount?: number;
            /** Format: int32 */
            firstBaronCount?: number;
            /** Format: double */
            firstBloodRatePct?: number;
            /** Format: double */
            firstTowerRatePct?: number;
            /** Format: double */
            firstDragonRatePct?: number;
            /** Format: double */
            firstHeraldRatePct?: number;
            /** Format: double */
            firstBaronRatePct?: number;
        };
        TeamPlayedChampionPlayerDto: {
            /** Format: int64 */
            playerId?: number;
            playerName?: string;
            playerImageUrl?: string;
            position?: string;
            champions?: components["schemas"]["TeamPlayedChampionStatDto"][];
        };
        TeamPlayedChampionSideStatsDto: {
            all?: components["schemas"]["TeamPlayedChampionPlayerDto"][];
            blue?: components["schemas"]["TeamPlayedChampionPlayerDto"][];
            red?: components["schemas"]["TeamPlayedChampionPlayerDto"][];
        };
        TeamPlayedChampionStatDto: {
            /** Format: int64 */
            championId?: number;
            championNameKr?: string;
            championNameEn?: string;
            championImageUrl?: string;
            /** Format: int32 */
            gamesPlayed?: number;
            /** Format: double */
            winRatePct?: number;
            /** Format: double */
            avgKda?: number;
            lastUsedAt?: string;
        };
        TeamPlayerRecordDto: {
            /** Format: int64 */
            playerId?: number;
            playerName?: string;
            playerImageUrl?: string;
            position?: string;
            /** Format: int32 */
            gamesPlayed?: number;
            /** Format: int32 */
            wins?: number;
            /** Format: int32 */
            losses?: number;
            /** Format: double */
            winRatePct?: number;
            /** Format: double */
            avgKda?: number;
            /** Format: double */
            avgKills?: number;
            /** Format: double */
            avgDeaths?: number;
            /** Format: double */
            avgAssists?: number;
            /** Format: int32 */
            firstKillCount?: number;
            /** Format: int32 */
            firstDeathCount?: number;
            /** Format: int32 */
            pentaKillCount?: number;
            /** Format: double */
            avgKillParticipationPct?: number;
            /** Format: double */
            avgDamageSharePct?: number;
            /** Format: double */
            avgGoldSharePct?: number;
            /** Format: double */
            avgVisionScore?: number;
            /** Format: double */
            avgVisionScorePerMinute?: number;
        };
        TeamScatterPointDto: {
            /** Format: int64 */
            teamId?: number;
            teamName?: string;
            teamCode?: string;
            teamImageUrl?: string;
            /** Format: int32 */
            gamesPlayed?: number;
            /** Format: double */
            winRatePct?: number;
            /** Format: double */
            avgOverall?: number;
            /** Format: double */
            avgKills?: number;
            /** Format: double */
            avgGold?: number;
            /** Format: double */
            avgObjectives?: number;
            /** Format: double */
            xvalue?: number;
        };
        TeamScatterResponse: {
            leagueName?: string;
            /** Format: int32 */
            year?: number;
            /** @enum {string} */
            metric?: "ALL" | "KILLS" | "GOLD" | "OBJECTIVES";
            points?: components["schemas"]["TeamScatterPointDto"][];
            xaxisLabel?: string;
            yaxisLabel?: string;
            /** Format: double */
            xleagueAverage?: number;
            /** Format: double */
            yleagueAverage?: number;
        };
        ChampionPickDto: {
            championName?: string;
            championImageUrl?: string;
            /** Format: int32 */
            playCount?: number;
            /** Format: double */
            winRate?: number;
            /** Format: double */
            banRate?: number;
            topOpponents?: components["schemas"]["OpponentChampionDto"][];
        };
        MostPickByPosition: {
            top?: components["schemas"]["ChampionPickDto"][];
            jungle?: components["schemas"]["ChampionPickDto"][];
            mid?: components["schemas"]["ChampionPickDto"][];
            bot?: components["schemas"]["ChampionPickDto"][];
            support?: components["schemas"]["ChampionPickDto"][];
        };
        OpponentChampionDto: {
            championName?: string;
            championImageUrl?: string;
            /** Format: int32 */
            matchCount?: number;
            /** Format: double */
            winRate?: number;
        };
        TeamRankingFilterDto: {
            /** Format: int32 */
            year?: number;
            splits?: string[];
            leagueNames?: string[];
            patch?: string;
            side?: string;
            effectiveSide?: string;
        };
        TeamRankingItemDto: {
            /** Format: int32 */
            rank?: number;
            /** Format: int64 */
            teamId?: number;
            teamName?: string;
            teamCode?: string;
            imageUrl?: string;
            /** Format: double */
            winRate?: number;
            /** Format: int32 */
            wins?: number;
            /** Format: int32 */
            losses?: number;
            /** Format: int32 */
            totalGames?: number;
            mostPicks?: components["schemas"]["MostPickByPosition"];
        };
        TeamRankingResponseDto: {
            rankings?: components["schemas"]["TeamRankingItemDto"][];
            /** Format: int32 */
            totalTeams?: number;
            appliedFilter?: components["schemas"]["TeamRankingFilterDto"];
        };
        TeamDetailStatsItemDto: {
            /** Format: int32 */
            rank?: number;
            /** Format: int64 */
            teamId?: number;
            teamName?: string;
            teamCode?: string;
            teamImageUrl?: string;
            /** Format: int32 */
            matchesPlayed?: number;
            /** Format: int32 */
            matchWins?: number;
            /** Format: int32 */
            matchLosses?: number;
            /** Format: int32 */
            setsPlayed?: number;
            /** Format: int32 */
            setWins?: number;
            /** Format: int32 */
            setLosses?: number;
            /** Format: double */
            winRatePct?: number;
            /** Format: double */
            avgKills?: number;
            /** Format: double */
            avgGold?: number;
            /** Format: double */
            avgBarons?: number;
            /** Format: double */
            avgDragons?: number;
            /** Format: double */
            avgTowers?: number;
            /** Format: int32 */
            firstBloodCount?: number;
            /** Format: int32 */
            firstTowerCount?: number;
            /** Format: int32 */
            firstDragonCount?: number;
            /** Format: int32 */
            firstHeraldCount?: number;
            /** Format: int32 */
            firstBaronCount?: number;
            /** Format: double */
            firstBloodRatePct?: number;
            /** Format: double */
            firstTowerRatePct?: number;
            /** Format: double */
            firstDragonRatePct?: number;
            /** Format: double */
            firstHeraldRatePct?: number;
            /** Format: double */
            firstBaronRatePct?: number;
        };
        TeamDetailStatsResponse: {
            leagueName?: string;
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            totalTeams?: number;
            items?: components["schemas"]["TeamDetailStatsItemDto"][];
        };
        PageVideoListResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["VideoListResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PageableObject: {
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
        };
        SortObject: {
            sorted?: boolean;
            empty?: boolean;
            unsorted?: boolean;
        };
        VideoListResponse: {
            /** Format: int64 */
            videoId?: number;
            youtubeVideoId?: string;
            title?: string;
            videoUrl?: string;
            thumbnailUrl?: string;
            channelType?: string;
            /** Format: date-time */
            publishedAt?: string;
            /** Format: int64 */
            viewCount?: number;
            /** Format: int64 */
            likeCount?: number;
            /** Format: int64 */
            commentCount?: number;
            /** Format: int64 */
            channelId?: number;
            channelName?: string;
            channelProfileUrl?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        CommentResponse: {
            youtubeCommentId?: string;
            authorDisplayName?: string;
            authorProfileImageUrl?: string;
            textDisplay?: string;
            /** Format: int64 */
            likeCount?: number;
            /** Format: date-time */
            publishedAt?: string;
        };
        PageCommentResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["CommentResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        MatchSummaryDto: {
            matchId?: string;
            scheduledTime?: string;
            leagueInfo?: string;
            matchTitle?: string;
            matchStatus?: string;
            isSynced?: boolean;
            teamA?: components["schemas"]["TeamResultDto"];
            teamB?: components["schemas"]["TeamResultDto"];
            liveStreamUrl?: string;
            sets?: components["schemas"]["SetVodDto"][];
        };
        ScheduleResponseDto: {
            date?: string;
            matches?: components["schemas"]["MatchSummaryDto"][];
        };
        SetVodDto: {
            /** Format: int32 */
            setNumber?: number;
            vodUrl?: string;
        };
        TeamResultDto: {
            teamName?: string;
            teamCode?: string;
            teamImageUrl?: string;
            /** Format: int32 */
            score?: number;
        };
        GameDetailDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int32 */
            gameNumber?: number;
            /** Format: int32 */
            gameLengthSeconds?: number;
            vodUrl?: string;
            blueTeam?: components["schemas"]["TeamPicksDto"];
            redTeam?: components["schemas"]["TeamPicksDto"];
        };
        MatchDetailResponseDto: {
            summary?: components["schemas"]["MatchSummaryDto"];
            gameDetails?: components["schemas"]["GameDetailDto"][];
        };
        PlayerPickDto: {
            position?: string;
            playerName?: string;
            championName?: string;
        };
        TeamPicksDto: {
            teamName?: string;
            isWin?: boolean;
            bans?: string[];
            players?: components["schemas"]["PlayerPickDto"][];
        };
        ScheduleCalendarResponseDto: {
            month?: string;
            dates?: components["schemas"]["ScheduleDateSummaryDto"][];
        };
        ScheduleDateSummaryDto: {
            date?: string;
            /** Format: int64 */
            matchCount?: number;
        };
        GameAccountDto: {
            region?: string;
            riotId?: string;
            tier?: string;
        };
        PlayerProfileDto: {
            gameName?: string;
            realName?: string;
            birthDate?: string;
            /** Format: int32 */
            age?: number;
            role?: string;
            gameAccounts?: components["schemas"]["GameAccountDto"][];
        };
        PlayerCardChampionDto: {
            /** Format: int64 */
            championId?: number;
            championNameKr?: string;
            championNameEn?: string;
            championImageUrl?: string;
            championLoadingImageUrl?: string;
            /** Format: int32 */
            playCount?: number;
            /** Format: double */
            winRatePct?: number;
        };
        PlayerCardFilterDto: {
            /** Format: int32 */
            year?: number;
            split?: string;
            patch?: string;
            side?: string;
        };
        PlayerCardItemDto: {
            /** Format: int64 */
            playerId?: number;
            playerName?: string;
            playerImageUrl?: string;
            teamCode?: string;
            teamImageUrl?: string;
            topChampionLoadingImageUrl?: string;
            mostChampions?: components["schemas"]["PlayerCardChampionDto"][];
            profile?: components["schemas"]["PlayerCardProfileDto"];
        };
        PlayerCardListResponse: {
            leagueName?: string;
            appliedFilter?: components["schemas"]["PlayerCardFilterDto"];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalCount?: number;
            /** Format: int32 */
            totalPages?: number;
            players?: components["schemas"]["PlayerCardItemDto"][];
        };
        PlayerCardProfileDto: {
            name?: string;
            position?: string;
            summonerName?: string;
            soloRankTier?: string;
            birthDate?: string;
            /** Format: int32 */
            gamesPlayed?: number;
            /** Format: double */
            kda?: number;
            /** Format: double */
            gpm?: number;
            /** Format: double */
            dpm?: number;
        };
        MatchResultDto: {
            matchId?: string;
            leagueName?: string;
            matchTitle?: string;
            matchDate?: string;
            state?: string;
            score?: string;
            blueTeam?: components["schemas"]["TeamInfo"];
            redTeam?: components["schemas"]["TeamInfo"];
            sets?: components["schemas"]["SetVod"][];
            liveStreamUrl?: string;
        };
        SetVod: {
            /** Format: int32 */
            setNumber?: number;
            vodUrl?: string;
        };
        TeamInfo: {
            externalTeamId?: string;
            code?: string;
            name?: string;
            imageUrl?: string;
            /** Format: int32 */
            wins?: number;
        };
        PlayerAnalysisResponse: {
            patchVersion?: string;
            seasonInfo?: string;
            kdaTop5?: components["schemas"]["PlayerStatsDto"][];
            gpmTop5?: components["schemas"]["PlayerStatsDto"][];
            dpmTop5?: components["schemas"]["PlayerStatsDto"][];
        };
        PlayerStatsDto: {
            teamName?: string;
            playerName?: string;
            playerImgUrl?: string;
            /** Format: int64 */
            totalGames?: number;
            /** Format: double */
            statValue?: number;
        };
        NewsPost: {
            /** Format: int64 */
            id?: number;
            title?: string;
            subContent?: string;
            thumbnail?: string;
            postUrl?: string;
            officeName?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUpdated?: string;
        };
        CommunityPost: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            communityType?: "OPGG" | "INVEN" | "NAVER";
            title?: string;
            author?: string;
            postUrl?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int32 */
            viewCount?: number;
            /** Format: int32 */
            voteCount?: number;
            /** Format: int32 */
            commentCount?: number;
            /** Format: date-time */
            lastUpdated?: string;
        };
        ChampionAnalysisResponse: {
            patchVersion?: string;
            seasonInfo?: string;
            topPicks?: components["schemas"]["ChampionStatsDto"][];
            topBans?: components["schemas"]["ChampionBanStatsDto"][];
        };
        ChampionBanStatsDto: {
            championNameKr?: string;
            championNameEn?: string;
            /** Format: int64 */
            banCount?: number;
            /** Format: double */
            banRate?: number;
            /** Format: int64 */
            totalGames?: number;
            /** Format: int64 */
            wins?: number;
            /** Format: double */
            winRate?: number;
            pickWinStats?: components["schemas"]["ChampionStatsDto"];
        };
        ChampionStatsDto: {
            championNameKr?: string;
            championNameEn?: string;
            /** Format: int64 */
            totalGames?: number;
            /** Format: int64 */
            wins?: number;
            /** Format: double */
            winRate?: number;
            /** Format: double */
            pickRate?: number;
        };
        GameResponseDto: {
            /** Format: int64 */
            gameId?: number;
            league?: string;
            patch?: string;
            /** Format: date-time */
            gameDate?: string;
            /** Format: int32 */
            gameLengthSeconds?: number;
            blueTeam?: components["schemas"]["TeamInGameDto"];
            redTeam?: components["schemas"]["TeamInGameDto"];
        };
        PageGameResponseDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["GameResponseDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PlayerInGameDto: {
            playerName?: string;
            championName?: string;
            position?: string;
        };
        TeamInGameDto: {
            teamName?: string;
            isWin?: boolean;
            side?: string;
            players?: components["schemas"]["PlayerInGameDto"][];
        };
        BansDto: {
            blue?: string[];
            red?: string[];
        };
        FearlessDto: {
            blue?: {
                [key: string]: string[];
            };
            red?: {
                [key: string]: string[];
            };
        };
        GameRecordDto: {
            gameid?: string;
            datacompleteness?: string;
            league?: string;
            /** Format: int32 */
            year?: number;
            split?: string;
            /** Format: int32 */
            playoffs?: number;
            date?: string;
            /** Format: int32 */
            game?: number;
            patch?: string;
            /** Format: int32 */
            gamelength?: number;
            bans?: components["schemas"]["BansDto"];
            fearless?: components["schemas"]["FearlessDto"];
            players?: components["schemas"]["PlayerRecordDto"][];
            setNav?: components["schemas"]["SetNavigationDto"];
        };
        PlayerRecordDto: {
            /** Format: int64 */
            participantid?: number;
            side?: string;
            position?: string;
            playername?: string;
            teamname?: string;
            champion?: string;
            /** Format: int32 */
            result?: number;
            /** Format: int32 */
            teamkills?: number;
            /** Format: int32 */
            teamdeaths?: number;
            firstblood?: boolean;
            firstdragon?: boolean;
            /** Format: int32 */
            dragons?: number;
            /** Format: int32 */
            oppDragons?: number;
            /** Format: int32 */
            elementaldrakes?: number;
            /** Format: int32 */
            oppElementaldrakes?: number;
            /** Format: int32 */
            infernals?: number;
            /** Format: int32 */
            mountains?: number;
            /** Format: int32 */
            clouds?: number;
            /** Format: int32 */
            oceans?: number;
            /** Format: int32 */
            chemtechs?: number;
            /** Format: int32 */
            hextechs?: number;
            /** Format: int32 */
            elders?: number;
            /** Format: int32 */
            oppElders?: number;
            firstherald?: boolean;
            /** Format: int32 */
            heralds?: number;
            /** Format: int32 */
            oppHeralds?: number;
            /** Format: int32 */
            voidGrubs?: number;
            /** Format: int32 */
            oppVoidGrubs?: number;
            firstbaron?: boolean;
            /** Format: int32 */
            barons?: number;
            /** Format: int32 */
            oppBarons?: number;
            firsttower?: boolean;
            /** Format: int32 */
            towers?: number;
            /** Format: int32 */
            oppTowers?: number;
            /** Format: int32 */
            turretPlates?: number;
            /** Format: int32 */
            oppTurretPlates?: number;
            /** Format: int32 */
            inhibitors?: number;
            /** Format: int32 */
            oppInhibitors?: number;
            /** Format: double */
            gspd?: number;
            /** Format: int32 */
            kills?: number;
            /** Format: int32 */
            deaths?: number;
            /** Format: int32 */
            assists?: number;
            /** Format: int32 */
            doubleKills?: number;
            /** Format: int32 */
            tripleKills?: number;
            /** Format: int32 */
            quadraKills?: number;
            /** Format: int32 */
            pentaKills?: number;
            isFirstBloodKill?: boolean;
            isFirstBloodAssist?: boolean;
            isFirstBloodVictim?: boolean;
            /** Format: int32 */
            damageToChampions?: number;
            /** Format: double */
            dpm?: number;
            /** Format: double */
            damageShare?: number;
            /** Format: double */
            damageTakenPerMinute?: number;
            /** Format: double */
            damageMitigatedPerMinute?: number;
            /** Format: int32 */
            wardsPlaced?: number;
            /** Format: double */
            wpm?: number;
            /** Format: int32 */
            wardsKilled?: number;
            /** Format: double */
            wcpm?: number;
            /** Format: int32 */
            controlWardsBought?: number;
            /** Format: double */
            visionScore?: number;
            /** Format: double */
            vspm?: number;
            /** Format: int32 */
            totalGold?: number;
            /** Format: int32 */
            earnedGold?: number;
            /** Format: double */
            earnedGpm?: number;
            /** Format: double */
            earnedGoldShare?: number;
            /** Format: int32 */
            goldSpent?: number;
            /** Format: int32 */
            totalCs?: number;
            /** Format: double */
            cspm?: number;
            /** Format: int32 */
            minionKills?: number;
            /** Format: int32 */
            monsterKills?: number;
            /** Format: int32 */
            goldAt10?: number;
            /** Format: int32 */
            oppGoldAt10?: number;
            /** Format: int32 */
            goldDiffAt10?: number;
            /** Format: int32 */
            xpAt10?: number;
            /** Format: int32 */
            oppXpAt10?: number;
            /** Format: int32 */
            xpDiffAt10?: number;
            /** Format: int32 */
            csAt10?: number;
            /** Format: int32 */
            oppCsAt10?: number;
            /** Format: int32 */
            csdiffAt10?: number;
            /** Format: int32 */
            killsAt10?: number;
            /** Format: int32 */
            assistsAt10?: number;
            /** Format: int32 */
            deathsAt10?: number;
            /** Format: int32 */
            oppKillsAt10?: number;
            /** Format: int32 */
            oppAssistsAt10?: number;
            /** Format: int32 */
            oppDeathsAt10?: number;
            /** Format: int32 */
            goldAt15?: number;
            /** Format: int32 */
            oppGoldAt15?: number;
            /** Format: int32 */
            goldDiffAt15?: number;
            /** Format: int32 */
            xpAt15?: number;
            /** Format: int32 */
            oppXpAt15?: number;
            /** Format: int32 */
            xpDiffAt15?: number;
            /** Format: int32 */
            csAt15?: number;
            /** Format: int32 */
            oppCsAt15?: number;
            /** Format: int32 */
            csdiffAt15?: number;
            /** Format: int32 */
            killsAt15?: number;
            /** Format: int32 */
            assistsAt15?: number;
            /** Format: int32 */
            deathsAt15?: number;
            /** Format: int32 */
            oppKillsAt15?: number;
            /** Format: int32 */
            oppAssistsAt15?: number;
            /** Format: int32 */
            oppDeathsAt15?: number;
            /** Format: int32 */
            goldAt20?: number;
            /** Format: int32 */
            oppGoldAt20?: number;
            /** Format: int32 */
            goldDiffAt20?: number;
            /** Format: int32 */
            xpAt20?: number;
            /** Format: int32 */
            oppXpAt20?: number;
            /** Format: int32 */
            xpDiffAt20?: number;
            /** Format: int32 */
            csAt20?: number;
            /** Format: int32 */
            oppCsAt20?: number;
            /** Format: int32 */
            csdiffAt20?: number;
            /** Format: int32 */
            killsAt20?: number;
            /** Format: int32 */
            assistsAt20?: number;
            /** Format: int32 */
            deathsAt20?: number;
            /** Format: int32 */
            oppKillsAt20?: number;
            /** Format: int32 */
            oppAssistsAt20?: number;
            /** Format: int32 */
            oppDeathsAt20?: number;
            /** Format: int32 */
            goldAt25?: number;
            /** Format: int32 */
            oppGoldAt25?: number;
            /** Format: int32 */
            goldDiffAt25?: number;
            /** Format: int32 */
            xpAt25?: number;
            /** Format: int32 */
            oppXpAt25?: number;
            /** Format: int32 */
            xpDiffAt25?: number;
            /** Format: int32 */
            csAt25?: number;
            /** Format: int32 */
            oppCsAt25?: number;
            /** Format: int32 */
            csdiffAt25?: number;
            /** Format: int32 */
            killsAt25?: number;
            /** Format: int32 */
            assistsAt25?: number;
            /** Format: int32 */
            deathsAt25?: number;
            /** Format: int32 */
            oppKillsAt25?: number;
            /** Format: int32 */
            oppAssistsAt25?: number;
            /** Format: int32 */
            oppDeathsAt25?: number;
        };
        SetInfo: {
            /** Format: int32 */
            setNumber?: number;
            /** Format: int64 */
            gameId?: number;
        };
        SetNavigationDto: {
            /** Format: int32 */
            currentSet?: number;
            /** Format: int32 */
            totalSets?: number;
            sets?: components["schemas"]["SetInfo"][];
            blueTeam?: components["schemas"]["TeamSummary"];
            redTeam?: components["schemas"]["TeamSummary"];
        };
        TeamSummary: {
            code?: string;
            name?: string;
            imageUrl?: string;
            /** Format: int32 */
            score?: number;
        };
        CombinationDetailDto: {
            summary?: components["schemas"]["CombinationResponseDto"];
            gameDetails?: components["schemas"]["GameDetailDto"][];
        };
        CombinationResponseDto: {
            combinationId?: string;
            /** Format: int32 */
            rank?: number;
            champions?: string[];
            /** Format: int64 */
            frequency?: number;
            /** Format: int64 */
            winCount?: number;
            /** Format: int64 */
            lossCount?: number;
            /** Format: double */
            winRate?: number;
            /** Format: date */
            latestGameDate?: string;
            latestPatch?: string;
        };
        UpdateInfoDto: {
            /** Format: date-time */
            lastUpdateTime?: string;
        };
        PageMatchupResponse: {
            /** Format: int32 */
            totalMatches?: number;
            /** Format: double */
            winRateForChampion1?: number;
            content?: components["schemas"]["GameDetailDto"][];
            pageable?: components["schemas"]["PageableObject"];
            hasNext?: boolean;
            /** Format: int64 */
            totalCount?: number;
        };
        PageCombinationResponse: {
            content?: components["schemas"]["CombinationResponseDto"][];
            pageable?: components["schemas"]["PageableObject"];
            hasNext?: boolean;
            /** Format: int64 */
            totalCount?: number;
        };
        ChampionDto: {
            /** Format: int64 */
            id?: number;
            championNameKr?: string;
            championNameEn?: string;
            imageUrl?: string;
            loadingImageUrl?: string;
        };
        CategoryTree: {
            seasons?: components["schemas"]["SeasonCategory"][];
        };
        LeagueCategory: {
            name?: string;
            splits?: components["schemas"]["SplitCategory"][];
        };
        SeasonCategory: {
            /** Format: int32 */
            year?: number;
            leagues?: components["schemas"]["LeagueCategory"][];
        };
        SplitCategory: {
            name?: string;
            /** Format: int64 */
            leagueId?: number;
            teams?: components["schemas"]["TeamSummary"][];
            patches?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    syncHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    updatePlayerImage: {
        parameters: {
            query: {
                imageUrl: string;
            };
            header?: never;
            path: {
                playerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    syncLckPlayerProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlayerProfileSyncResult"];
                };
            };
        };
    };
    syncLckPlayerImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlayerImageSyncResult"];
                };
            };
        };
    };
    syncPrimaryRiotAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlayerRiotAccountSyncResult"];
                };
            };
        };
    };
    pollTrackedPlayers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlayerSoloRankMonitorResult"];
                };
            };
        };
    };
    checkAndSendRiotAlert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerRiotAlertCheckRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlayerRiotAlertCheckResult"];
                };
            };
        };
    };
    getSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KakaoSkillRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["KakaoSkillResponse"];
                };
            };
        };
    };
    getLckSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["KakaoSkillRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["KakaoSkillResponse"];
                };
            };
        };
    };
    updateChampionLoadingImage: {
        parameters: {
            query: {
                imageUrl: string;
            };
            header?: never;
            path: {
                championId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    syncChampions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    updateAllChampionLoadingImages: {
        parameters: {
            query?: {
                overwrite?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    syncAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    syncTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    syncPlayers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    autocomplete: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchAutocompleteResponse"];
                };
            };
        };
    };
    getTeamRadarStats: {
        parameters: {
            query?: {
                /**
                 * @description 연도 (기본값: 2026)
                 * @example 2026
                 */
                year?: number;
            };
            header?: never;
            path: {
                /** @description 팀 ID */
                teamId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamRadarResponse"];
                };
            };
        };
    };
    getTeamProfileHeader: {
        parameters: {
            query?: {
                /**
                 * @description 리그명 (기본값: LCK)
                 * @example LCK
                 */
                league?: string;
            };
            header?: never;
            path: {
                /** @description 팀 ID */
                teamId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamProfileHeaderResponse"];
                };
            };
        };
    };
    getTeamDashboard: {
        parameters: {
            query?: {
                /**
                 * @description 리그명 (기본값: LCK)
                 * @example LCK
                 */
                league?: string;
                /**
                 * @description 연도 (기본값: 2026)
                 * @example 2026
                 */
                year?: number;
                /** @description 스플릿 (예: Round 1-2) */
                split?: string;
                /** @description 패치 (예: 14.1) */
                patch?: string;
                /**
                 * @description 진영 필터 (ALL, BLUE, RED) - 선수기록(playerRecords)에만 적용
                 * @example ALL
                 */
                side?: string;
            };
            header?: never;
            path: {
                /** @description 팀 ID */
                teamId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamDashboardResponse"];
                };
            };
        };
    };
    getTeamScatterStats: {
        parameters: {
            query?: {
                /**
                 * @description 연도 (기본값: 2026)
                 * @example 2026
                 */
                year?: number;
                /**
                 * @description 리그명 (기본값: LCK)
                 * @example LCK
                 */
                league?: string;
                /**
                 * @description x축 지표 (ALL, KILLS, GOLD, OBJECTIVES)
                 * @example ALL
                 */
                metric?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamScatterResponse"];
                };
            };
        };
    };
    getTeamRankings: {
        parameters: {
            query?: {
                /** @description 경기 연도 (예: 2026) */
                year?: number;
                /** @description 스플릿 목록 (예: Round 1-2, Cup) */
                splits?: string[];
                /** @description 리그 이름 목록 (예: LCK, LPL) */
                leagueNames?: string[];
                /** @description 패치 버전 (예: 14.1) */
                patch?: string;
                /** @description 진영 필터 (ALL, Blue, Red) */
                side?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamRankingResponseDto"];
                };
            };
        };
    };
    getTeamDetailStats: {
        parameters: {
            query?: {
                /**
                 * @description 연도 (기본값: 2026)
                 * @example 2026
                 */
                year?: number;
                /**
                 * @description 리그명 (기본값: LCK)
                 * @example LCK
                 */
                league?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TeamDetailStatsResponse"];
                };
            };
        };
    };
    getVideos: {
        parameters: {
            query?: {
                /**
                 * @description 카테고리 (all: 전체, pro: 프로팀, shorts: 쇼츠 채널)
                 * @example all
                 */
                category?: string;
                /**
                 * @description 정렬 기준 (latest: 최신순, views: 조회수순, likes: 좋아요순)
                 * @example latest
                 */
                sort?: string;
                /**
                 * @description 기간 필터 (all: 전체, week: 최근 1주, month: 최근 1달)
                 * @example all
                 */
                period?: string;
                /**
                 * @description 페이지 번호 (0부터 시작)
                 * @example 0
                 */
                page?: number;
                /**
                 * @description 페이지 크기
                 * @example 20
                 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageVideoListResponse"];
                };
            };
        };
    };
    getVideoComments: {
        parameters: {
            query: {
                /**
                 * @description 정렬 기준 (recent: 최신순, popular: 인기순)
                 * @example recent
                 */
                sort?: string;
                /** @description 페이징 정보 (기본 20개) */
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                /** @description 유튜브 비디오 ID */
                videoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageCommentResponse"];
                };
            };
        };
    };
    getDailySchedule: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScheduleResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getMatchDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MatchDetailResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getMonthlyScheduleCalendar: {
        parameters: {
            query: {
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScheduleCalendarResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getPlayerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 선수 활동명
                 * @example Faker
                 */
                gameName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlayerProfileDto"];
                };
            };
        };
    };
    getPlayerCards: {
        parameters: {
            query?: {
                /**
                 * @description 리그명 (기본값: LCK)
                 * @example LCK
                 */
                league?: string;
                /**
                 * @description 연도 (기본값: 2026)
                 * @example 2026
                 */
                year?: number;
                /** @description 스플릿 (예: Round 3-5) */
                split?: string;
                /** @description 패치 (예: 14.1) */
                patch?: string;
                /**
                 * @description 진영 필터 (ALL, BLUE, RED)
                 * @example ALL
                 */
                side?: string;
                /**
                 * @description 페이지 번호(1-base)
                 * @example 1
                 */
                page?: number;
                /**
                 * @description 페이지 크기
                 * @example 20
                 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlayerCardListResponse"];
                };
            };
        };
    };
    getMatchThumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/svg+xml": string;
                };
            };
        };
    };
    getSchedule_1: {
        parameters: {
            query?: {
                /**
                 * @description 조회할 날짜 (YYYY-MM-DD)
                 * @example 2026-01-04
                 */
                date?: string;
                /**
                 * @description 리그 이름 (ALL, LCK, LPL 등)
                 * @example ALL
                 */
                league?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MatchResultDto"][];
                };
            };
        };
    };
    getTop5Players: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlayerAnalysisResponse"];
                };
            };
        };
    };
    getTop5News: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NewsPost"][];
                };
            };
        };
    };
    getTop5CommunityPosts: {
        parameters: {
            query?: {
                /**
                 * @description 정렬 기준 (latest: 최신순, popular: 인기순)
                 * @example latest
                 */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommunityPost"][];
                };
            };
        };
    };
    getTop5Champions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChampionAnalysisResponse"];
                };
            };
        };
    };
    getRecentGames: {
        parameters: {
            query?: {
                year?: number;
                leagueNames?: string[];
                splits?: string[];
                teamNames?: string[];
                page?: number;
                size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageGameResponseDto"];
                };
            };
        };
    };
    getGameRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gameId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GameRecordDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getCombinationDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 조합 고유 ID */
                combinationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CombinationDetailDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getUpdateInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UpdateInfoDto"];
                };
            };
        };
    };
    get1v1Matchup: {
        parameters: {
            query: {
                /**
                 * @description 내 챔피언 (기준)
                 * @example Ahri
                 */
                champion1: string;
                /**
                 * @description 상대 챔피언
                 * @example Azir
                 */
                champion2: string;
                year?: number;
                splits?: string[];
                leagueNames?: string[];
                teamNames?: string[];
                patch?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageMatchupResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getCombinationsV2: {
        parameters: {
            query: {
                /** @description 포함할 챔피언 이름 리스트 (예: Ahri,Galio) */
                champions: string[];
                /** @description 경기 연도 (미입력 시 전체) */
                year?: number;
                /** @description 스플릿 (Cup, Rounds 1-2 등) */
                splits?: string[];
                /** @description 리그 이름 (LCK, LPL 등) */
                leagueNames?: string[];
                /** @description 팀 이름 */
                teamNames?: string[];
                /** @description 게임 패치 버전 */
                patch?: string;
                /** @description 페이지 번호 (0부터 시작) */
                page?: number;
                /** @description 페이지 크기 */
                size?: number;
                /** @description 정렬 기준 (frequency) */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageCombinationResponse"];
                };
            };
        };
    };
    getAllChampions: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChampionDto"][];
                };
            };
        };
    };
    getCategoryTree: {
        parameters: {
            query?: {
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CategoryTree"];
                };
            };
        };
    };
    resetAllPlayerImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
}
